### ISSUE TITLE
Elemental Mastery Buff consumed by wrong Spells

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2701]
Originally reported by: **Reid (Bitbucket: [reidbetten](https://bitbucket.org/reidbetten), GitHub: Unknown)**

---

Water Shield and Lightning Shield (and other spells) will consume Elemental Mastery if they proc.

Elemental Mastery is only supposed to be consumed by Shaman frost, nature, and fire offensive spells.

---

Elemental mastery doesn't work as intended, ive pretty much figured out whats wrong with it however.

The way its suppose to work is, it should make the next spell cast after applying the buff having 100% crit and cost 0 mana. That means it should NOT make a spell already traveling crit if you pop it while your for example lightning bolt is in the air.

At the moment the only way to make sure you get the 100% crit is to pop it, cast a spell and wait for it to land before you start casting your next spell, also if you get hit while elemental mastery is up and you have lightning shield, it seems to make your spell not crit aswell.

So atm it doesnt crit if you pop it, cast a spell for example lightningbolt and then start casting another spell before it lands. neither will crit.

If you cast a lightning bolt and you pop it when the spell is in the air but dont cast anything else until it lands, that lightning bolt will crit and eat the buff wich is also not working as intended.

Popping it and instantly using a shock is pretty much the only way to be sure it works at this point.

As you can see alot needs fixing with this and im really hoping you can get all of this in, since the most popular combo and best way of using it is casting lightningbolt then popping elemental mastery for a chainlightning, so if the bugg that it will make your already airborne spell crits instead remains, its still messing things up abit.

---

Hi there just reporting a bug. 39805 Lightning Overload (LO) - Elemental Shaman talent. combinated with 6164 Elemental Focus (EF) Doesn't work as intended...

When you get EF from crit it gives you 2 charges of Clearcasting. Means next 2 damage spells have their mana cost reduced by 40%.

But.. when at same time procs LO that gives EXTRA copy of your spell, it takes 1 clearcasting charge.. even if it is free spell (no mana needed).

So when you want to use (4example) ChainLightning after you get Clearcasting.. you cannot get that when you cant even count with LO that will grab one of them.

```
with Clearcasting buff you have always 2 stacks even when you already casted 1 away.
```

If you combine this with Elemental Mastery bug.. that lets even your already casted spell to crit (and cost mana even if its for next spell) You can lose Clearcasting with Elemental Mastery together just for LO.

I'm marking this bug as major because it is 3 talents together not working properly, so you cannot play as elemental shaman with mana efficiency.

Elemental mastery is broken totaly. Even if you start it up before you are in combat.. then start casting it, and cancel casting (or being kicked, or even posponed casting from some dmg to you) it will dissapear... So 4example if you are under atack of few mobs.. you want to live so you want to kill them quickly.. starting Elemental Mastery and casting Chain Lightning is waste of cd because it will dissapear without ANY effect.

**Comment by AnonXS** [comment]
-- spell_proc_event
-- 30675,30678,30679,30680,30681 -- 39805

I need more info, is this new? and it should not happen if this is works and gets applied:

https://github.com/NostalriusTBC/Core/pull/27/files

spellmods dont get consumed when casting spells with zero cost

tested this after my changes from yesterday and can not reproduce lightning overload proccs using clearcasting.

faking is still poison.

// without fake

Blitzschlag von Name trifft Player Combat Dummy für 32 Naturschaden. (Kritisch)
Freizaubern von Name wird aufgefrischt.
Name erhält Freizaubern.
Blitzschlag von Name trifft Player Combat Dummy für 8 Naturschaden.
Name beginnt, Blitzschlag zu wirken.
Blitzschlag von Name trifft Player Combat Dummy für 16 Naturschaden.
Name beginnt, Blitzschlag zu wirken.
Blitzschlag von Name trifft Player Combat Dummy für 16 Naturschaden.
Freizaubern schwindet von Name.

// with fake 
Namekann Blitzschlag nicht wirken. (Unterbrochen)
Namebeginnt, Blitzschlag zu wirken.
Namekann Blitzschlag nicht wirken. (Unterbrochen)
Freizaubern schwindet von Name .

**Comment by AnonXS** [comment]
-- spell_proc_event
-- 30675,30678,30679,30680,30681 -- 39805

I need more info, is this new? and it should not happen if this is works and gets applied:

https://github.com/NostalriusTBC/Core/pull/27/files

spellmods dont get consumed when casting spells with zero cost

tested this after my changes from yesterday and can not reproduce lightning overload proccs using clearcasting.

faking is still poison.

// without fake

Blitzschlag von Name trifft Player Combat Dummy für 32 Naturschaden. (Kritisch)
Freizaubern von Name wird aufgefrischt.
Name erhält Freizaubern.
Blitzschlag von Name trifft Player Combat Dummy für 8 Naturschaden.
Name beginnt, Blitzschlag zu wirken.
Blitzschlag von Name trifft Player Combat Dummy für 16 Naturschaden.
Name beginnt, Blitzschlag zu wirken.
Blitzschlag von Name trifft Player Combat Dummy für 16 Naturschaden.
Freizaubern schwindet von Name.

// with fake 
Namekann Blitzschlag nicht wirken. (Unterbrochen)
Namebeginnt, Blitzschlag zu wirken.
Namekann Blitzschlag nicht wirken. (Unterbrochen)
Freizaubern schwindet von Name .

**Comment by AdmCrunch** [comment]
AnonXS,

Not sure about the lightning overload consuming elemental mastery.  There are so many things consuming the buff and I can only test every 3 min, so it's tough to nail them all down.

That said, if you do this combination, the elemental mastery buff is consumed without granting 100% crit chance to any spells.

 Lightning Bolt -> Elemental Mastery -> Chain Lightning (while 1st Lightning Bolt is in the air) 

A video of this happening is here:  https://youtu.be/v2EwxrgD3aI

**Comment by Emarka** [comment]
Basically any buff you gain consumes Elemental Mastery, I was losing it by gaining warriors Battle Shout for example. As for clearcasting it works oddly as well sometimes ok, sometimes both stacks disapear at once.

**Comment by AnonXS** [comment]
**Elemental Mastery gets triggered from Lightning Shield when I get hit. That is not supposed to happen, and it also gets triggered if I use after it cast a spell and lightning overload poccs. It does not make any of there spells crit.**

**Comment by Zergfest** [comment]
Seeing as this issue was initially reported 9 months ago, can we expect it to be fixed any time soon? This has a great impact in elemental viability both in pvp and pve. Especially Elemental Mastery.

**Comment by natas94** [comment]
I recorded the bug happening (it wasn't hard since it has 100% repeteability), when Elemental Mastery buff got consumed from a lightning bolt that was already flying, rendering the buff useless. At the moment there is no way to use Elemental Mastery efficiently unless it is the first spell that you cast after moving.

[Example here](https://plays.tv/s/LDiNpbNqbf5e)

**Comment by sefamurat** [comment]
This is complete bullshit. An entire shaman spec is being irrelevant because of a bugfest specific to that spec. As stated above, the issue is almost a year old. I invested a lot of time to play my elem shaman here not knowing it wasn't scripted to a playable level. If elem shaman problems are not fixed soon I will take this to wowservers reddit to showcase dev incompetence. This is not a problem that only affects elemental shamans, absence of one spec affects the entire game meta.

**Comment by miraco** [comment]
Maybe this:
https://bitbucket.org/Caboon/playcore-official/commits/359a2bc9ae696a496dac83e157a336256edb376a?at=default

**Comment by AnonXS** [comment]
that commit was reverted shortly after.

**Comment by Rythex** [comment]
I can confirm this behaviour. Manaspring totem triggered it this time.
[https://www.dropbox.com/s/ldnubdp5feqwa9x/Capture_senthex.PNG?dl=0](url)

**Comment by AbaddonL4G** [comment]
`                else if (spellInfo->Id == 16166) // Elemental Mastery
                    spellInfo->EffectItemType[0] = 2416967683; // Dec value for SpellFamilyFlags of Frost Shock, Earth Shock, Flame Shock, Lighning Bolt, Chain Lightning
                    spellInfo->EffectItemType[1] = 2416967683; `

**Comment by AbaddonL4G** [comment]
```cpp
                else if (spellInfo->Id == 16166) // Elemental Mastery
                    spellInfo->EffectItemType[0] = 2416967683; // Dec value for SpellFamilyFlags of Frost Shock, Earth Shock, Flame Shock, Lighning Bolt, Chain Lightning
                    spellInfo->EffectItemType[1] = 2416967683;

**Comment by AnonXS** [comment]
We have a rather root bug bypassing fix in test phase on the PTR Realm.
Problem with that is that as long as EM is active, the shaman is not able to procc anything else, so EM gets consumed, crits with chain lightening but doesnt procc clearcast, but in my opinion, working EM is alot more worth then loosing one Clearcast Procc.

Togther with another branch i set up it is possible to mitigate the bug produced by the EM bugfix.
By Delaying the appliaction of EM by around 1second it is possible for the flying lightning bolt to crit, proc clearcast, Cast EM, EM not consumed by that flying Lightning Bolt and crit with a Chainlightning with 100%crit have the Clearcast procc on you (CL will not be able to procc Clearcast with EM active) but still have it when the Lightining bolt at the start critted.

**Comment by natas94** [comment]
Even thou it's only a workaround, I think that what you have explained is a big improvement to the current state of the spell. The only case where it would not work correctly is if you want to use EM + shock, where (if I've understood it correctly) the instant shock would not proc the delayed EM.

**Comment by Rythex** [comment]
At least the class "Spell" would need an additional attribute to indicate if a spell is active casted or passive. E.g. passive spells would be mana totem or healing totem.

How is that behaviour handled with cold blood from rogue? The cast is nearly the same as EM.

Regards

Senthex

**Comment by Pbeitelmann** [comment]
This has been fixed. Elemental Mastery is no longer consumed by Spells that already have been midair when the Elemental Mastery buff is gained.

**Comment by Rythex** [comment]
Not fixed! My trinket, or manashield often still consumes my EM. When I cast EM and press Manashield with a 0,5 sec delay it gets consumed.

**Comment by AnonXS** [comment]
https://github.com/OregonCore/OregonCore/commit/ad92b9bd428755e52b5ccf8ee9ce8053a0b194d6

**Comment by AbaddonL4G** [comment]
Just add what ive done above - should fix the bug that its consumed by other spells

**Comment by AleskiWeb** [comment]
Just came to say that I am still experiencing this. Infact if a LBOLT is in the air, as i pop EM, then its consumed as it lands and is NOT a crit but i still lose the buff.
