### ISSUE TITLE
SSC/Lady Vashj: Mind Control - MC'ed ppl can be stunned/gouged

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2927]
As in the topic, during Lady vashj encounter on phase 3 ppl can be stunned / gouged during Mind Control

How should it work? they shouldn't be stunnable or gouge'able.

**Comment by Pbeitelmann** [comment]
This was fixed with [this](https://github.com/Looking4Group/L4G_Core/commit/778a5744b2fb4d9f7b1c6c8033d1e0f26466d695) and should not occur anymore.

**Comment by Anteara** [comment]
Hi, did you experience this last week, or more recent?
As Pbe said, we did a fix for it.
If it was recent, then the fix might not have worked.

**Comment by Selphius** [comment]
It wasn't fixed, we could stun etc. MC'ed ppl on this ID, + you have fresh video from yesterday kill from Inquisition.

Fast example: https://www.twitch.tv/dualityinq/v/95352577
Time: 02:59:08
You can look for more if you wish :P

**Comment by Maple7** [comment]
Hi, Maple here from Inquisition.
I can confirm that the issue is not fixed. Honestly, we were not aware that MC'd players should be immune to all forms of CC, including stuns. Hence, we did knowingly take advantage of this, if the question should arrise. 
I would also like to question whether MC'd players should be able to get the debuff  'static charge'? While under the influence of MC the player should technically be friendly to Lady Vashj and therfore not be subject to this debuff. Yesterday we experienced MC'd players dying to this debuff whilst dealing AoE damage to everyone in their path.

**Comment by AbaddonL4G** [comment]
As far as i know only the paladin stun is working

**Comment by Maple7** [comment]
My rogue CL can confirm that his stuns does indeed work. This does include cheap- and kidney-shot. Gouge on the other hand does not work.

**Comment by Selphius** [comment]
Concusion Blow from warrior also works.

@Maple7 Don't worry about taking advantage of it, since every guild takes advantage of it at the moment :P The same was when MC could be feared/traped etc. everyone took advantage, since one only care about a swift kill rather than fair kill without using such methods.

**Comment by NihnInq** [comment]
Dunno if a Priest Blackout works.. R1 spells to proc. Worth to look at.

**Comment by Selphius** [comment]
I suggest changing label from invalid, since it isn't invalid in the first place. Proofs were shown :>

**Comment by Selphius** [comment]
Any progress on it? since Vashj is too easy right now, with soft enrage timer wrong + this. Later fix for it won't even be noticed since ppl will be too overgeared.

**Comment by AnonXS** [comment]
This resolved with https://github.com/Looking4Group/L4G_Core/commit/778a5744b2fb4d9f7b1c6c8033d1e0f26466d695.
