### ISSUE TITLE
Akama questchain!

### ISSUE THREAD

**Issue by Diverse1** [Looking4Group/L4G_Core#3107]
So when you do the Akama questchain in Shadowmoon Valley, after the RP event where Akama "kills you" some characters remain in that animation, regardless of relogging, clearing cache etc. You're still able to cast spells, mount up and everything, but your character remains in the "dead" animation.

I've been like this for 2 days now.
Someone care to fix it/me?
Thanks

**Comment by Diverse1** [comment]
![wowscrnshot_122416_013222](https://cloud.githubusercontent.com/assets/24740225/21464287/f13013d2-c978-11e6-878e-8712588beda0.jpg)

/rip

**Comment by AbaddonL4G** [comment]
should be fixed with https://github.com/Looking4Group/L4G_Core/pull/3108

**Comment by Diverse1** [comment]
It's not fixed.
I am still very much in the "dead" animation.
